### ISSUE TITLE
yeah i'd kill myself if i had to use this

### ISSUE THREAD

**Issue by halal** [cristeigabriel/HelvetaCS#1]
why?

**Comment by cristeigabriel** [comment]
ok

**Comment by RXVAN** [comment]
its not actually that bad at all,
really clean styling, yeah some code is questionable, mainly within the ESP imo, but that's nothing you can't change yourself.
everything else about it is cool IMO, i love the idea of the console for configging things, its a really good idea + reminds me of the good ol' days;)
anyways, just sucks to see kids hating on something based on something they either have 0 knowledge of or who havent even attempted to look at it properly :/

**Comment by poIak** [comment]
Polak approves of Helveta
